# Generated by Django 3.2.5 on 2022-04-28 08:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 8, 10, 21, 246542, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 8, 10, 21, 246542, tzinfo=utc)),
        ),
    ]
